<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <link href='https://fonts.googleapis.com/css?family=Chivo:900' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/kbarchive/assets/css/style.css?v=d2057ae472d963fbdcbf65805f43123bccb709dc">
    <link rel="stylesheet" type="text/css" href="/kbarchive/assets/css/print.css" media="print">
    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Begin Jekyll SEO tag v2.5.0 -->
<title>Q246550: BUG: Local Static Variables Not Reinitialized after an Exception | KnowledgeBase Archive</title>
<meta name="generator" content="Jekyll v3.8.5" />
<meta property="og:title" content="Q246550: BUG: Local Static Variables Not Reinitialized after an Exception" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="An Archive of Early Microsoft KnowledgeBase Articles" />
<meta property="og:description" content="An Archive of Early Microsoft KnowledgeBase Articles" />
<link rel="canonical" href="http://jeffpar.github.io/kbarchive/kb/246/Q246550/" />
<meta property="og:url" content="http://jeffpar.github.io/kbarchive/kb/246/Q246550/" />
<meta property="og:site_name" content="KnowledgeBase Archive" />
<script type="application/ld+json">
{"headline":"Q246550: BUG: Local Static Variables Not Reinitialized after an Exception","url":"http://jeffpar.github.io/kbarchive/kb/246/Q246550/","description":"An Archive of Early Microsoft KnowledgeBase Articles","@type":"WebPage","@context":"http://schema.org"}</script>
<!-- End Jekyll SEO tag -->

</head>

<body>
<div id="container">
    <div class="inner">

        <header>
            <h1><a href="/kbarchive">KnowledgeBase Archive</a></h1>
            <h2>An Archive of Early Microsoft KnowledgeBase Articles</h2>
        </header>
        <section id="downloads" class="clearfix">
            
            
            <a href="https://github.com/jeffpar/kbarchive" id="view-on-github" class="button"><span>View on GitHub</span></a>
            
        </section>
        <hr>
        <section id="main_content">
                <div>
        <h2 id="q246550-bug-local-static-variables-not-reinitialized-after-an-exception">Q246550: BUG: Local Static Variables Not Reinitialized after an Exception</h2>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>Article: Q246550
Product(s): Microsoft C Compiler
Version(s): winnt:6.0
Operating System(s): 
Keyword(s): kbCPPonly kbVC600bug kbDSupport
Last Modified: 03-MAY-2001

-------------------------------------------------------------------------------
The information in this article applies to:

- The C/C++ Compiler (CL.EXE), included with:
   - Microsoft Visual C++, 32-bit Enterprise Edition, version 6.0 
   - Microsoft Visual C++, 32-bit Professional Edition, version 6.0 
   - Microsoft Visual C++, 32-bit Learning Edition, version 6.0 
-------------------------------------------------------------------------------

SYMPTOMS
========

After the constructor for a local static variable throws an exception, the
constructor is not called the next time there is a call to the function in which
the variable is declared.

CAUSE
=====

The Visual C++ Compiler has not correctly implemented the behavior dictated by
the ANSI C++ specification. The ANSI specification, section 6.7 states in part:

  "The zero-initialization [construction] of all local objects with static
  storage duration is performed before any other initialization takes place.
  ... such an object is initialized the first time control passes through its
  declaration; such an object is considered initialized upon the completion of
  its initialization [upon completion of its constructor] . If the
  initializations exits by throwing an exception, the initialization is not
  complete, so it will be tried again [constructor called again] the next time
  control enters the declaration. ..."

RESOLUTION
==========

There are several potential ways to workaround the behavior, including removing
the static keyword from the variable declaration, having the class constructor
catch and handle the exception, not using exceptions, using a separate
initialization function to emulate proper behavior, and so forth. The actual
approach you choose will be greatly dependent upon your individual project. See
the "More Information" section for an example of the separate initialization
approach.

STATUS
======

Microsoft has confirmed this to be a bug in the Microsoft products listed at the
beginning of this article.

MORE INFORMATION
================

Steps to Reproduce Behavior
---------------------------

The following code sample illustrates the problem. Define the "workaround to see
the separate initialization function approach.

  // compile options:  /GX 
  #include &lt;iostream&gt;

  class MyClass
  {
  public:
       MyClass() { throw(int()); }
       MyClass(const MyClass&amp; cClass) {}
       MyClass&amp; operator=(const MyClass &amp;co) {return *this;}
       virtual ~MyClass() {}
  };

  #ifdef WORKAROUND
  class MyClassWrapper : public MyClass
  {
  public:
  // Here, m_InitFlag is set to false in the initialize list
  // (Before MyClass() is called), and then set to true
  // in the body of the constructor (after MyClass() is called)
       MyClassWrapper() : m_InitFlag(false) {m_InitFlag = true;}
       void init()
       {
            if(!m_InitFlag)
            {
                 MyClass tmp;
                 *((MyClass *)this) = tmp;
                 m_InitFlag = true;
            }
       }
  private:
  	bool m_InitFlag;
  };
  #endif //WORKAROUND

  #ifdef WORKAROUND
  typedef MyClassWrapper StaticClass;
  #else
  typedef MyClass StaticClass;
  #endif //WORKAROUND

  void MyFunction()
  { 
  	static StaticClass MyObject;
  #ifdef WORKAROUND
  	MyObject.init();
  #endif //WORKAROUND
  }

  int main()
  {
       using std::cout;

       for(int i = 0; i &lt; 2; i++)
       {
            try
            {
                 MyFunction();
                 cout &lt;&lt; "No Exceptions Thrown / All Exceptions Handled\n";
            }
            catch(int)
            {
                 cout &lt;&lt; "An int Exception Was Thrown and Not Handled\n";
            }
       }

       return 0;
  }
  // end program

Output:

An int Exception Was Thrown and Not Handled
No Exceptions Thrown / All Exceptions Handled

Output if WORKAROUND defined:

An int Exception Was Thrown and Not Handled
An int Exception Was Thrown and Not Handled

Additional query words: Exception Constructor ANSI

======================================================================
Keywords          : kbCPPonly kbVC600bug kbDSupport 
Technology        : kbVCsearch kbAudDeveloper kbCVCComp
Version           : winnt:6.0
Issue type        : kbbug
Solution Type     : kbpending

=============================================================================
</code></pre></div></div>


        <p>
            THE INFORMATION PROVIDED IN THE MICROSOFT KNOWLEDGE BASE IS
            PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND.  MICROSOFT DISCLAIMS
            ALL WARRANTIES, EITHER EXPRESS OR IMPLIED, INCLUDING THE WARRANTIES
            OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  IN NO
            EVENT SHALL MICROSOFT CORPORATION OR ITS SUPPLIERS BE LIABLE FOR
            ANY DAMAGES WHATSOEVER INCLUDING DIRECT, INDIRECT, INCIDENTAL,
            CONSEQUENTIAL, LOSS OF BUSINESS PROFITS OR SPECIAL DAMAGES, EVEN IF
            MICROSOFT CORPORATION OR ITS SUPPLIERS HAVE BEEN ADVISED OF THE
            POSSIBILITY OF SUCH DAMAGES.  SOME STATES DO NOT ALLOW THE EXCLUSION
            OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES
            SO THE FOREGOING LIMITATION MAY NOT APPLY.
        </p>
        <p>Copyright Microsoft Corporation 1986-2002.</p>
    </div>

        </section>

        <footer>
            
            KnowledgeBase Archive is maintained by <a href="https://www.pcjs.org">PCjs</a>.<br>
            
            This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.
        </footer>

    </div>
</div>


<script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-49658648-3', 'auto');
    ga('send', 'pageview');
</script>

</body>
</html>