<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <link href='https://fonts.googleapis.com/css?family=Chivo:900' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/kbarchive/assets/css/style.css?v=d2057ae472d963fbdcbf65805f43123bccb709dc">
    <link rel="stylesheet" type="text/css" href="/kbarchive/assets/css/print.css" media="print">
    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Begin Jekyll SEO tag v2.5.0 -->
<title>Q157073: PRB: Exception Not Caught Using CArchive or CFile | KnowledgeBase Archive</title>
<meta name="generator" content="Jekyll v3.8.5" />
<meta property="og:title" content="Q157073: PRB: Exception Not Caught Using CArchive or CFile" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="An Archive of Early Microsoft KnowledgeBase Articles" />
<meta property="og:description" content="An Archive of Early Microsoft KnowledgeBase Articles" />
<link rel="canonical" href="http://jeffpar.github.io/kbarchive/kb/157/Q157073/" />
<meta property="og:url" content="http://jeffpar.github.io/kbarchive/kb/157/Q157073/" />
<meta property="og:site_name" content="KnowledgeBase Archive" />
<script type="application/ld+json">
{"headline":"Q157073: PRB: Exception Not Caught Using CArchive or CFile","url":"http://jeffpar.github.io/kbarchive/kb/157/Q157073/","description":"An Archive of Early Microsoft KnowledgeBase Articles","@type":"WebPage","@context":"http://schema.org"}</script>
<!-- End Jekyll SEO tag -->

</head>

<body>
<div id="container">
    <div class="inner">

        <header>
            <h1><a href="/kbarchive">KnowledgeBase Archive</a></h1>
            <h2>An Archive of Early Microsoft KnowledgeBase Articles</h2>
        </header>
        <section id="downloads" class="clearfix">
            
            
            <a href="https://github.com/jeffpar/kbarchive" id="view-on-github" class="button"><span>View on GitHub</span></a>
            
        </section>
        <hr>
        <section id="main_content">
                <div>
        <h2 id="q157073-prb-exception-not-caught-using-carchive-or-cfile">Q157073: PRB: Exception Not Caught Using CArchive or CFile</h2>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>Article: Q157073
Product(s): Microsoft C Compiler
Version(s): winnt:2.0,2.1,2.2,4.0,4.1,4.2
Operating System(s): 
Keyword(s): kbFileIO kbMFC kbVC200 kbVC400 kbVC420 kbGrpDSMFCATL kbExceptHandCPP kbExceptHandling
Last Modified: 04-AUG-2001

-------------------------------------------------------------------------------
The information in this article applies to:

- The Microsoft Foundation Classes (MFC), used with:
   - Microsoft Visual C++, 32-bit Editions, versions 2.0, 2.1, 2.2, 4.0, 4.1 
   - Microsoft Visual C++, 32-bit Enterprise Edition, version 4.2 
   - Microsoft Visual C++, 32-bit Professional Edition, version 4.2 
-------------------------------------------------------------------------------

SYMPTOMS
========

When using CArchive or CFile, Visual C++ exceptions may not be caught if the
CArchive and/or CFile are in the same try block as a read or write:

     void Test1()
     {
          try {
             //Drive A: should contain a floppy with zero bytes free
             CFile file("A:\\BadFile.tmp", CFile::modeCreate
                        | CFile::shareExclusive | CFile::modeWrite );
             try {
                 CArchive archive(&amp;file, CArchive::store);
                 //Fill up disk, and cause a
                 //CFileException::diskFull exception
                 while(1)
                     archive &lt;&lt; (DWORD)17;
             }
             catch ( CFileException* ex ) {
                 ex-&gt;Delete();
             }
             catch (...) {
                 ASSERT(FALSE);
             }
         }
         catch ( CFileException* ex ) {
             ex-&gt;Delete();
         }
         catch (...){
             ASSERT(FALSE);
         }
     }

In this case, if the disk is full, the exception is not caught, terminate() is
called, and the application exits.

CAUSE
=====

In the process of handling exceptions, objects inside the try block are
destructed before the first catch block. During unwinding, when a second
exception is thrown by a destructor before the first exception is caught,
terminate() is called.

Both the destructors for CArchive and CFile attempt to flush the buffer and close
the open file. This can cause a second exception to get thrown and terminate()
to get called.

RESOLUTION
==========

Make sure that the CArchive or CFile object is not inside the same try block as
any read or write on that object.

The CArchive object should also not be inside of the same try block as the CFile
object it uses unless the CArchive was created in the CArchive::bNoFlushOnDelete
mode. If this mode is used, the CArchive and CFile can safely be in the same try
block. Care must be taken to call CArchive::Flush() before the CArchive is
deleted, and in a separate try block. The second example below shows using a
CArchive in this mode.

STATUS
======

This behavior is by design.

MORE INFORMATION
================

This is a behavior of Visual C++ exception handling and did not occur with
earlier versions of MFC, which did not use C++ exception handling.

Sample Code
-----------

Example 1
---------

     // This example shows placing CFile, CArchive, and writes in separate
     // try blocks
     /* Compile options needed: default AppWizard application
     */ 
     void Test2()
     {
         try {
             //Drive A: should contain a floppy with zero bytes free
             CFile file("A:\\BadFile.tmp", CFile::modeCreate
                        | CFile::shareExclusive | CFile::modeWrite );
             try {
                 CArchive archive(&amp;file, CArchive::store);
                 try {
                     //Fill up disk, and cause a
                     // CFileException::diskFull exception
                     while(1)
                         archive &lt;&lt; (DWORD)17;
                 }
                 catch ( CFileException* ex ) {
                     archive.Abort();
                     ex-&gt;Delete();
                 }
                 catch (...){
                     ASSERT(FALSE);
                 }
             }
             catch ( CFileException* ex ) {
                 file.Abort();
                 ex-&gt;Delete();
             }
             catch (...){
                  ASSERT(FALSE);
             }
         }
         catch ( CFileException* ex ) {
             ex-&gt;Delete();
         }
         catch (...){
             ASSERT(FALSE);
         }
     }

Example 2
---------

     // This example uses CArchive::bNoFlushOnDelete so that CFile and
     // CArchive can be placed in the same try block.
     /* Compile options needed: default AppWizard application
     */ 
     void Test3()
     {
          try {
             //Drive A: should contain a floppy with zero bytes free
             CFile file("A:\\BadFile.tmp",
                 CFile::modeCreate | CFile::shareExclusive
                             | CFile::modeWrite );
             CArchive archive(&amp;file,
                 CArchive::store | CArchive::bNoFlushOnDelete);
             try {
                 //Fill up disk, and cause a CFileException::diskFull
                 //exception
                 while(1)
                     archive &lt;&lt; (DWORD)17;
                 //Manually flush archive in try-block
                 archive.Flush();
             }
             catch ( CFileException* ex ) {
                 archive.Abort();
                 ex-&gt;Delete();
             }
             catch (...){
                 ASSERT(FALSE);
             }
         }
         catch ( CFileException* ex ) {
             ex-&gt;Delete();
         }
         catch (...){
             ASSERT(FALSE);
         }
     }

Additional query words: 2.00 2.10 2.20 4.00 4.10 4.20 kbdsd CArchive CFile Exception

======================================================================
Keywords          : kbFileIO kbMFC kbVC200 kbVC400 kbVC420 kbGrpDSMFCATL kbExceptHandCPP kbExceptHandling 
Technology        : kbAudDeveloper kbMFC
Version           : winnt:2.0,2.1,2.2,4.0,4.1,4.2
Issue type        : kbprb

=============================================================================
</code></pre></div></div>


        <p>
            THE INFORMATION PROVIDED IN THE MICROSOFT KNOWLEDGE BASE IS
            PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND.  MICROSOFT DISCLAIMS
            ALL WARRANTIES, EITHER EXPRESS OR IMPLIED, INCLUDING THE WARRANTIES
            OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  IN NO
            EVENT SHALL MICROSOFT CORPORATION OR ITS SUPPLIERS BE LIABLE FOR
            ANY DAMAGES WHATSOEVER INCLUDING DIRECT, INDIRECT, INCIDENTAL,
            CONSEQUENTIAL, LOSS OF BUSINESS PROFITS OR SPECIAL DAMAGES, EVEN IF
            MICROSOFT CORPORATION OR ITS SUPPLIERS HAVE BEEN ADVISED OF THE
            POSSIBILITY OF SUCH DAMAGES.  SOME STATES DO NOT ALLOW THE EXCLUSION
            OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES
            SO THE FOREGOING LIMITATION MAY NOT APPLY.
        </p>
        <p>Copyright Microsoft Corporation 1986-2002.</p>
    </div>

        </section>

        <footer>
            
            KnowledgeBase Archive is maintained by <a href="https://www.pcjs.org">PCjs</a>.<br>
            
            This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.
        </footer>

    </div>
</div>


<script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-49658648-3', 'auto');
    ga('send', 'pageview');
</script>

</body>
</html>